script-dir: /opt/ci/files/nodepool-scripts
dburi: 'mysql://nodepool@localhost/nodepool'

cron:
  check: '*/1 * * * *'

zmq-publishers:
  - tcp://127.0.0.1:8888

gearman-servers:
  - host: 127.0.0.1

labels:
  - name:  trusty-42
    image: trusty-42
    min-ready: 3
    providers:
      - name: cilab-1
  - name:  trusty-43
    image: trusty-43
    min-ready: 3
    providers:
      - name: cilab-2

providers:
  - name: cilab-1
    username: 'ci-user'
    password: 'nova'
    auth-url: 'http://172.18.168.42:5000/v2.0'
    project-id: 'ci'
    max-servers: 6
    boot-timeout: 120
    pool: public
    networks:
      - net-id: 'LAB_42_PRIVATE_NETWORK_ID'
    images:
      - name: trusty-42
        base-image: 'ubuntu-14.04'
        min-ram: 2048
        private-key: '/etc/nodepool/id_dsa'
        setup: prepare_node.sh
  - name: cilab-2
    username: 'ci-user'
    password: 'nova'
    auth-url: 'http://172.18.168.43:5000/v2.0'
    project-id: 'ci'
    max-servers: 6
    boot-timeout: 120
    pool: public
    networks:
      - net-id: 'LAB_43_PRIVATE_NETWORK_ID'
    images:
      - name: trusty-43
        base-image: 'ubuntu-14.04'
        min-ram: 2048
        private-key: '/etc/nodepool/id_dsa'
        setup: prepare_node.sh

targets:
  - name: sahara-gate
    jenkins:
      url: http://127.0.0.1/jenkins
      user: admin
      apikey: JENKINS_API_KEY
      credentials-id: CREDENTIALS_ID
